# Generated by Django 4.2.11 on 2026-02-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_customuser_managers_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_oauth_user',
            field=models.BooleanField(default=False, verbose_name='Người dùng OAuth'),
        ),
    ]
