# Generated by Django 4.2.11 on 2026-02-24 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_brand_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='HangingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL Ảnh bên ngoài')),
                ('image_local', models.ImageField(blank=True, null=True, upload_to='hanging_products/', verbose_name='Ảnh sản phẩm')),
                ('original_price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Giá gốc (VNĐ)')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='% Giảm giá')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng trong kho')),
                ('installment_0_percent', models.BooleanField(default=False, verbose_name='Trả góp 0%')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hanging_products', to='store.brand', verbose_name='Hãng sản xuất')),
            ],
            options={
                'verbose_name': 'Sản phẩm treo',
                'verbose_name_plural': 'Sản phẩm treo',
                'ordering': ['-created_at'],
            },
        ),
    ]
