# Generated by Django 4.2.11 on 2026-02-24 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_hangingproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangingproduct',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hanging_products', to='store.brand', verbose_name='Hãng sản xuất'),
        ),
    ]
