# Generated by Django 4.2.11 on 2026-02-24 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_hangingproduct_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Giá gốc (VNĐ)')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='% Giảm giá')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='SKU chung')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='store.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Chi tiết sản phẩm',
                'verbose_name_plural': 'Chi tiết sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50, verbose_name='Tên màu')),
                ('color_hex', models.CharField(blank=True, max_length=7, verbose_name='Mã màu (hex)')),
                ('storage', models.CharField(max_length=20, verbose_name='Dung lượng')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Giá (VNĐ)')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='SKU biến thể')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng trong kho')),
                ('is_active', models.BooleanField(default=True, verbose_name='Còn hàng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.productdetail', verbose_name='Chi tiết sản phẩm')),
            ],
            options={
                'verbose_name': 'Biến thể sản phẩm',
                'verbose_name_plural': 'Biến thể sản phẩm',
                'unique_together': {('detail', 'color_name', 'storage')},
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('cover', 'Ảnh đại diện'), ('marketing', 'Ảnh marketing/banner'), ('variant_thumbnail', 'Ảnh màu (thumbnail)'), ('variant_main', 'Ảnh màu (chính)'), ('variant_gallery', 'Ảnh màu (gallery)'), ('variant_detail', 'Ảnh màu (chi tiết)')], default='cover', max_length=20, verbose_name='Loại ảnh')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Ảnh')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.productdetail', verbose_name='Chi tiết sản phẩm')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.productvariant', verbose_name='Biến thể')),
            ],
            options={
                'verbose_name': 'Hình ảnh sản phẩm',
                'verbose_name_plural': 'Hình ảnh sản phẩm',
                'ordering': ['order'],
            },
        ),
    ]
