# Generated by Django 4.2.11 on 2026-02-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_productdetail_productvariant_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Giá (VNĐ)'),
        ),
    ]
