# Generated by Django 4.2.11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_discount_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Thư mục ảnh')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug thư mục')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'store_imagefolder',
                'verbose_name': 'Thư mục ảnh',
                'verbose_name_plural': 'Thư mục ảnh',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FolderColorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, verbose_name='SKU')),
                ('color_name', models.CharField(max_length=100, verbose_name='Màu sản phẩm')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Ảnh')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folder_images', to='store.brand', verbose_name='Hãng')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.imagefolder', verbose_name='Thư mục ảnh')),
            ],
            options={
                'db_table': 'store_foldercolorimage',
                'verbose_name': 'Ảnh màu theo thư mục',
                'verbose_name_plural': 'Ảnh màu theo thư mục',
                'ordering': ['folder__name', 'color_name', 'order'],
            },
        ),
    ]
