# Generated by Django 4.2.11 on 2026-02-24 17:58

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_productvariant_original_price_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foldercolorimage',
            name='image',
            field=models.ImageField(upload_to=store.models.image_folder_upload_path, verbose_name='Ảnh'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Giá sau giảm (VNĐ)'),
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_json', models.JSONField(blank=True, default=dict, verbose_name='Thông số kỹ thuật (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='store.productdetail', verbose_name='Chi tiết sản phẩm')),
            ],
            options={
                'verbose_name': 'Thông số kỹ thuật sản phẩm',
                'verbose_name_plural': 'Thông số kỹ thuật sản phẩm',
            },
        ),
    ]
