# Generated by Django 4.2.11 on 2026-02-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_foldercolorimage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_id', models.CharField(max_length=50, verbose_name='ID Banner')),
                ('image', models.ImageField(upload_to='banner/%Y/%m/', verbose_name='Ảnh Banner')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
                'ordering': ['banner_id', '-created_at'],
            },
        ),
    ]
