# Generated by Django 4.2.11 on 2026-02-25 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_text', models.TextField(blank=True, verbose_name='Nội dung text')),
                ('image', models.ImageField(blank=True, upload_to='product_content/%Y/%m/', verbose_name='Ảnh minh họa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_contents', to='store.brand', verbose_name='Hãng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_contents', to='store.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Nội dung sản phẩm',
                'verbose_name_plural': 'Nội dung sản phẩm',
                'ordering': ['-created_at'],
                'unique_together': {('brand', 'product')},
            },
        ),
    ]
