# Generated by Django 4.2.11 on 2026-02-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='youtube_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='YouTube Video ID'),
        ),
    ]
