# Generated by Django 4.2.11 on 2026-02-25 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_add_youtube_id_to_productdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian đổi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='Trình duyệt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Lịch sử đổi mật khẩu',
                'verbose_name_plural': 'Lịch sử đổi mật khẩu',
                'ordering': ['-changed_at'],
            },
        ),
    ]
