# Generated by Django 4.2.11 on 2026-02-25 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_passwordhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Họ tên')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('province_code', models.CharField(max_length=10, verbose_name='Mã tỉnh/thành')),
                ('province_name', models.CharField(max_length=100, verbose_name='Tỉnh/Thành phố')),
                ('district_code', models.CharField(max_length=10, verbose_name='Mã quận/huyện')),
                ('district_name', models.CharField(max_length=100, verbose_name='Quận/Huyện')),
                ('ward_code', models.CharField(max_length=10, verbose_name='Mã phường/xã')),
                ('ward_name', models.CharField(max_length=100, verbose_name='Phường/Xã')),
                ('detail', models.CharField(max_length=500, verbose_name='Địa chỉ chi tiết')),
                ('is_default', models.BooleanField(default=False, verbose_name='Địa chỉ mặc định')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Địa chỉ',
                'verbose_name_plural': 'Địa chỉ',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
