# Generated by Django 4.2.11 on 2026-02-26 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_pending_qr_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='VNPayPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Số tiền')),
                ('order_code', models.CharField(max_length=50, unique=True, verbose_name='Mã đơn hàng VNPay')),
                ('transaction_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã giao dịch VNPay')),
                ('transaction_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mã trạng thái VNPay')),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('failed', 'Thất bại'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('response_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Response code VNPay')),
                ('response_message', models.CharField(blank=True, max_length=255, null=True, verbose_name='Response message VNPay')),
                ('pay_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phương thức thanh toán')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian thanh toán')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vnpay_payments', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Thanh toán VNPay',
                'verbose_name_plural': 'Thanh toán VNPay',
                'ordering': ['-created_at'],
            },
        ),
    ]
