# Generated by Django 4.2.11 on 2026-02-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_vnpay_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(default='QHUN00000', max_length=20, unique=True, verbose_name='Mã đơn hàng'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'COD'), ('vietqr', 'VietQR'), ('vnpay', 'VNPay')], default='cod', max_length=20, verbose_name='Phương thức TT'),
        ),
        migrations.AddField(
            model_name='order',
            name='vnpay_order_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã VNPay'),
        ),
    ]
