# Generated by Django 4.2.11 on 2026-02-26 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_order_code_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('color_name', models.CharField(blank=True, max_length=50, verbose_name='Màu')),
                ('storage', models.CharField(blank=True, max_length=20, verbose_name='Dung lượng')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Đơn giá')),
                ('thumbnail', models.CharField(blank=True, max_length=500, verbose_name='Ảnh thumbnail URL')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order', verbose_name='Đơn hàng')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='store.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Sản phẩm đơn hàng',
                'verbose_name_plural': 'Sản phẩm đơn hàng',
            },
        ),
    ]
