# Generated by Django 4.2.11 on 2026-02-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_account',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Số tài khoản hoàn tiền'),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_bank',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ngân hàng hoàn tiền'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Đã đặt hàng'), ('processing', 'Đang xử lý'), ('shipped', 'Đang giao'), ('delivered', 'Đã giao hàng'), ('cancelled', 'Hủy đơn')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
