# Generated by Django 4.2.11 on 2026-02-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_add_refund_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(blank=True, choices=[('', 'Chưa yêu cầu'), ('pending', 'Chờ hoàn tiền'), ('completed', 'Đã hoàn tiền')], default='', max_length=20, verbose_name='Trạng thái hoàn tiền'),
        ),
    ]
