# Generated by Django 4.2.11 on 2026-02-27 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefolder',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_folders', to='store.brand', verbose_name='Hãng'),
        ),
        migrations.AddField(
            model_name='imagefolder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_folders', to='store.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='imagefolder',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Thư mục ảnh'),
        ),
        migrations.AlterField(
            model_name='imagefolder',
            name='slug',
            field=models.SlugField(max_length=150, verbose_name='Slug thư mục'),
        ),
        migrations.AlterUniqueTogether(
            name='imagefolder',
            unique_together={('name', 'brand', 'product')},
        ),
    ]
