# Generated by Django 4.2.11 on 2026-02-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_add_product_to_hangingproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Chờ thanh toán'), ('pending', 'Đã đặt hàng'), ('processing', 'Đang xử lý'), ('shipped', 'Đang giao'), ('delivered', 'Đã giao hàng'), ('cancelled', 'Hủy đơn')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
