# Generated by Django 4.2.11 on 2026-02-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_add_awaiting_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã giảm giá')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Mô tả')),
                ('discount_type', models.CharField(choices=[('percentage', 'Phần trăm (%)'), ('fixed', 'Số tiền cố định (đ)')], default='percentage', max_length=20, verbose_name='Loại giảm giá')),
                ('discount_value', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Giá trị giảm')),
                ('min_order_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Đơn tối thiểu')),
                ('max_discount', models.DecimalField(decimal_places=0, default=0, help_text='Chỉ áp dụng cho loại phần trăm. 0 = không giới hạn', max_digits=15, verbose_name='Giảm tối đa')),
                ('usage_limit', models.PositiveIntegerField(default=0, help_text='0 = không giới hạn', verbose_name='Giới hạn sử dụng')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Đã sử dụng')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('start_date', models.DateTimeField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateTimeField(verbose_name='Ngày kết thúc')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Mã giảm giá',
                'verbose_name_plural': 'Mã giảm giá',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Mã giảm giá'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Số tiền giảm'),
        ),
    ]
