# Generated by Django 4.2.11 on 2026-02-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_coupon_order_coupon_code_order_discount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='description',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='max_discount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='start_date',
        ),
        migrations.AddField(
            model_name='coupon',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày hết hạn'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='expire_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Hạn sử dụng (ngày)'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_products',
            field=models.PositiveIntegerField(default=0, help_text='Số SP tối đa được áp dụng. 0 = không giới hạn', verbose_name='Giới hạn sản phẩm'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Tên chương trình'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='target_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email áp dụng'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='target_type',
            field=models.CharField(choices=[('all', 'Mọi người'), ('single', '1 người')], default='all', max_length=10, verbose_name='Đối tượng'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tên mã giảm'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Giảm %'), ('fixed', 'Giảm số tiền')], default='percentage', max_length=20, verbose_name='Kiểu giảm giá'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Còn sử dụng'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(default=0, help_text='0 = không giới hạn', verbose_name='Giới hạn lượt dùng'),
        ),
    ]
