# Generated by Django 4.2.11 on 2026-02-28 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_remove_coupon_description_remove_coupon_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_student_verified',
            field=models.BooleanField(default=False, verbose_name='Đã xác thực Student'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_teacher_verified',
            field=models.BooleanField(default=False, verbose_name='Đã xác thực Teacher'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày xác thực Student'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='teacher_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày xác thực Teacher'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verified_student_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email Student đã xác thực'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verified_teacher_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email Teacher đã xác thực'),
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email xác thực')),
                ('code', models.CharField(max_length=6, verbose_name='Mã xác thực')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Đã xác thực')),
                ('verification_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=20, verbose_name='Loại xác thực')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('expires_at', models.DateTimeField(verbose_name='Thời gian hết hạn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xác thực email',
                'verbose_name_plural': 'Xác thực email',
                'ordering': ['-created_at'],
            },
        ),
    ]
