# Generated by Django 4.2.11 on 2026-03-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_couponusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian đăng ký')),
            ],
            options={
                'verbose_name': 'Đăng ký nhận tin',
                'verbose_name_plural': 'Đăng ký nhận tin',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='couponusage',
            options={'ordering': ['-used_at'], 'verbose_name': 'Lịch sử dụng voucher', 'verbose_name_plural': 'Lịch sử dụng voucher'},
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(default=0, help_text='Số lần mỗi người dùng được tối đa. 0 = không giới hạn', verbose_name='Giới hạn lượt dùng (mỗi người)'),
        ),
    ]
