# Generated by Django 4.2.11 on 2026-03-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_newsletter_add_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='momo_order_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã MoMo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'COD'), ('vietqr', 'VietQR'), ('vnpay', 'VNPay'), ('momo', 'MoMo')], default='cod', max_length=20, verbose_name='Phương thức TT'),
        ),
    ]
