# Generated by Django 4.2.11 on 2026-03-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_order_momo_order_code_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Nội dung đánh giá'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='images',
            field=models.JSONField(default=list, verbose_name='Ảnh đánh giá (tối đa 3)'),
        ),
    ]
