# Generated by Django 4.2.11 on 2026-03-21 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_add_sample_blog_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBrowseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian xem')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='browse_logs', to='store.brand', verbose_name='Hãng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browse_logs', to='store.product', verbose_name='Sản phẩm')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='browse_logs', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Log xem sản phẩm',
                'verbose_name_plural': 'Log xem sản phẩm',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user', 'brand'], name='store_userb_user_id_c95a6e_idx'), models.Index(fields=['ip_address', 'brand'], name='store_userb_ip_addr_3b78db_idx')],
            },
        ),
    ]
